curiosity/main/routes.py
from flask import render_template, Blueprint, request

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home", methods=['GET', 'POST'])
def home():
    return render_template('home.html')

    query = request.form['query']
    if query:
        return redirect(url_for('results.result_page'), link=link)

@main.route("/about", methods=['GET', 'POST'])
def about():
    return render_template('about_us.html')

curiosity/results/routes.py
from flask import render_template, Blueprint, request, redirect, url_for
from youtubesearchpython import *
from curiosity.main.utils import meta_dict_corp,train_model, query_result

results = Blueprint('results', __name__)


@results.route("/results", methods=['GET', 'POST'])
def result_page():
    query = request.form['query']

    meta_dict_corp()
    train_model()
    episode_num, timestamp = query_result(query)

    playlist = Playlist('https://www.youtube.com/playlist?list=PLrAXtmErZgOdP_8GztsuKi9nrraNbKKp4')

    while playlist.hasMoreVideos:
        playlist.getNextVideos()
    for video in playlist.videos:
        if episode_num in video['title']:
            link = video['id']

    return render_template('results.html', link=link, start=timestamp-20, end=timestamp+300)

curiosity/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from curiosity import db, bcrypt
from curiosity.models import User, Post
from curiosity.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from curiosity.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='assets/profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

curiosity/templates/About us.html
{% extends "layout.html" %}
{% block content %}
    <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <h1 class="mx-auto my-0 text-uppercase">About Us>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5">The place where you start your journey into the </h2>
                    <a class="btn btn-primary" href="#about">Get Started</a>
                </div>
            </div>
        </div>
    </header>

    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8">
                    <h2 class="text-white mb-4">Start the journey!</h2>
                    <p class="text-white-50">
                        Curiosity is your door to the release your mind
                        <a href="https://startbootstrap.com/theme/grayscale/">Check it out!</a>
                        You research will be improved!
                    </p>
                </div>
            </div>
            <img class="img-fluid" src="https://th.bing.com/th/id/OIG.OWGpA8aFrZx4HFQC7.AJ?pid=ImgGn" alt="..." />
        </div>
    </section>
{% endblock content %}

curiosity/templates/About_us.html
{% extends "layout.html" %}
{% block content %}
    <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <h1 class="mx-auto my-0 text-uppercase">About us</h1>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5">We are a team of students from different background to explore the world of IT and Computer Science!</h2>
                </div>
            </div>
        </div>
    </header>

    <div class="row abus-section abus-info">
        <!-- main content area -->

        <div class="col-sm-9 col-lg-4 col-md-9 col-xs-9">
          <a href="https://www.linkedin.com/in/alessandro-lupo96/">
              <div id="ale-linkedin" class="img-responsive"><span>Alessandro </br> Lupo</span></div>
          </a>
          <h2><a href="https://www.linkedin.com/in/alessandro-lupo96/"> LinkedIn</a></h2>
          <p> <strong>Has a strong background in Quantum Computing and its applications in life. Experienced in project management </strong> </p>
          <p> Doing master’s in Digital Transformation Management and is studying topics linked to the world of computer science, digitalization, programming and database systems.</p>
          <p> 2022 - till now, the University of Bologna </p>
          <h3> Contacts:</h3>
          <ul>
          <li>Mobile phone: +39 327 744 5147
          </li>
          <li>LinkedIn: https://www.linkedin.com/in/alessandro-lupo96/
          </li>
          <li>Email: alessandro.lupo.1996la96@gmail.com
          </li>
          </ul>
        </div>

        <div class="col-sm-9 col-lg-4 col-md-9 col-xs-9">
          <a href="https://www.linkedin.com/in/javokhir-isomurodov/">
            <div id="java-linkedin" class="img-responsive"><span>Javokhir </br>Isomurodov</span></div>
          </a>
          <h2><a href="https://www.linkedin.com/in/javokhir-isomurodov/"> LinkedIn</a></h2>
          <p><strong> Is passionate about Artificial Intelligence and Machine Learning. Has been working actively on telemedicine lately </strong></p>
          <p> Doing master’s in Digital Transformation Management and is studying topics linked to the world of computer science, digitalization, programming and database systems.</p>
          <p> 2022 - till now, the University of Bologna </p>
              <h3> Contacts:</h3>
          <ul>
          <li>Mobile phone: +39 377 387 1618
          </li>
          <li>LinkedIn: https://www.linkedin.com/in/javokhir-isomurodov/
          </li>
          <li>Email: mr.isomurodov@gmail.com
          </li>
          </ul>
        </div>

        <div class="col-sm-9 col-lg-4 col-md-9 col-xs-9">
          <a href="https://www.linkedin.com/in/dildora-abdurakhmanova/">
            <div id="dilyan-linkedin" class="img-responsive"><span>Dildora </br> Abdurakhmanova</span></div>
          </a>
          <h2><a href="https://www.linkedin.com/in/dildora-abdurakhmanova/"> LinkedIn</a></h2>
          <p><strong> Did bachelor’s in Accounting. Is involved in software quality control with main focus on mobile applications</strong> </p>
          <p> Doing master’s in Digital Transformation Management and is studying topics linked to the world of computer science, digitalization, programming and database systems.</p>
          <p> 2022 - till now, the University of Bologna </p>
              <h3> Contacts:</h3>
          <ul>
          <li>Mobile phone: +39 329 362 9003
          </li>
          <li>LinkedIn: https://www.linkedin.com/in/dildora-abdurakhmanova/
          </li>
          <li>Email: abduraxmanova2298@gmail.com
          </li>
          </ul>
        </div>
      </div>

    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8">
                    <h2 class="text-white mb-4">Start the journey!</h2>
                    <p class="text-white-50">
                        Let's explore your favourite topic!
                        You research will be improved!
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

curiosity/templates/about_us.html
{% extends "layout.html" %}
{% block content %}
    <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <h1 class="mx-auto my-0 text-uppercase">About us</h1>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5">We are a team of students from different background to explore the world of IT and Computer Science!</h2>
                </div>
            </div>
        </div>
    </header>

    <div class="row abus-section abus-info">
        <!-- main content area -->

        <div class="col-sm-9 col-lg-4 col-md-9 col-xs-9">
          <a href="https://www.linkedin.com/in/alessandro-lupo96/">
              <div id="ale-linkedin" class="img-responsive"><span>Alessandro </br> Lupo</span></div>
          </a>
          <h2><a href="https://www.linkedin.com/in/alessandro-lupo96/"> LinkedIn</a></h2>
          <p> <strong>Has a strong background in Quantum Computing and its applications in life. Experienced in project management </strong> </p>
          <p> Doing master’s in Digital Transformation Management and is studying topics linked to the world of computer science, digitalization, programming and database systems.</p>
          <p> 2022 - till now, the University of Bologna </p>
          <h3> Contacts:</h3>
          <ul>
          <li>Mobile phone: +39 327 744 5147
          </li>
          <li>LinkedIn: https://www.linkedin.com/in/alessandro-lupo96/
          </li>
          <li>Email: alessandro.lupo.1996la96@gmail.com
          </li>
          </ul>
        </div>

        <div class="col-sm-9 col-lg-4 col-md-9 col-xs-9">
          <a href="https://www.linkedin.com/in/javokhir-isomurodov/">
            <div id="java-linkedin" class="img-responsive"><span>Javokhir </br>Isomurodov</span></div>
          </a>
          <h2><a href="https://www.linkedin.com/in/javokhir-isomurodov/"> LinkedIn</a></h2>
          <p><strong> Is passionate about Artificial Intelligence and Machine Learning. Has been working actively on telemedicine lately </strong></p>
          <p> Doing master’s in Digital Transformation Management and is studying topics linked to the world of computer science, digitalization, programming and database systems.</p>
          <p> 2022 - till now, the University of Bologna </p>
              <h3> Contacts:</h3>
          <ul>
          <li>Mobile phone: +39 377 387 1618
          </li>
          <li>LinkedIn: https://www.linkedin.com/in/javokhir-isomurodov/
          </li>
          <li>Email: mr.isomurodov@gmail.com
          </li>
          </ul>
        </div>

        <div class="col-sm-9 col-lg-4 col-md-9 col-xs-9">
          <a href="https://www.linkedin.com/in/dildora-abdurakhmanova/">
            <div id="dilyan-linkedin" class="img-responsive"><span>Dildora </br> Abdurakhmanova</span></div>
          </a>
          <h2><a href="https://www.linkedin.com/in/dildora-abdurakhmanova/"> LinkedIn</a></h2>
          <p><strong> Did bachelor’s in Accounting. Is involved in software quality control with main focus on mobile applications</strong> </p>
          <p> Doing master’s in Digital Transformation Management and is studying topics linked to the world of computer science, digitalization, programming and database systems.</p>
          <p> 2022 - till now, the University of Bologna </p>
              <h3> Contacts:</h3>
          <ul>
          <li>Mobile phone: +39 329 362 9003
          </li>
          <li>LinkedIn: https://www.linkedin.com/in/dildora-abdurakhmanova/
          </li>
          <li>Email: abduraxmanova2298@gmail.com
          </li>
          </ul>
        </div>
      </div>

    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8">
                    <h2 class="text-white mb-4">Start the journey!</h2>
                    <p class="text-white-50">
                        Let's explore your favourite topic!
                        You research will be improved!
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

curiosity/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="mb-3">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="mb-3">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="mb-3">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="mb-3">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="mb-3">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

curiosity/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <h1 class="mx-auto my-0 text-uppercase">CURIOSITY</h1>
                    <h2 class="text-white-50 mx-auto mt-2 mb-5">The place where you start your journey into the </h2>
                    <div class="container">
                        <form action="/results" method="POST" id="search">
                            <div class="form-group">
                                <input type="text" class="form-control" name="query" placeholder="Enter your search query">
                            </div>
                            <button type="submit" class="btn btn-primary">Search</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8">
                    <h2 class="text-white mb-4">Start the journey!</h2>
                    <p class="text-white-50">
                        Let's explore your favourite topic!
                        <a href="http://localhost:63342/STOCS/curiosity/templates/About_us.html?_ijt=815nh3r9lckirnapdcr5sr83v0&_ij_reload=RELOAD_ON_SAVE">Check it out!</a>
                        You research will be improved!
                    </p>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

curiosity/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>Curiosity</title>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="static/css/styles.css">
    </head>

    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav"
             {% if title %}
                style="background-color: rgba(130,162,165,0.61)"
             {% endif %}
        >
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{{ url_for('main.home') }}">Curiosity</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About Us</a>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Masthead-->
        <div id="main-content">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <!-- Core theme JS-->
        <script src="../static/js/script.js"></script>
    </body>
</html>

curiosity/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" id="forms">
            {{ form.hidden_tag() }}
            <fieldset class="mb-3">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="mb-3">
                    {{ form.email.label(class="form-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                </div>
                <div class="mb-3">
                    {{ form.password.label(class="form-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control") }}
                    {% endif %}
                </div>
                <div class="mb-3 form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>

            <div class="mb-3">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2" id="forgot-pass">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

curiosity/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

curiosity/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="mb-3">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="mb-3">
                    {{ form.email.label(class="form-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="mb-3">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

curiosity/templates/results.html
{% extends "layout.html" %}
{% block content %}
    <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <h1 class="mx-auto my-0 text-uppercase">CURIOSITY</h1>
                    <iframe id="ytplayer" type="text/html" width="640" height="360"
                            src="https://www.youtube.com/embed/{{link}}?&start={{start}}&end={{end}}"
                            frameborder="0">
                    </iframe>
            </div>
        </div>
    </header>

    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8">
                    <h2 class="text-white mb-4">Built with Bootstrap 5</h2>
                    <p class="text-white-50">
                        Grayscale is a free Bootstrap theme created by Start Bootstrap. It can be yours right now, simply download the template on
                        <a href="https://startbootstrap.com/theme/grayscale/">the preview page.</a>
                        The theme is open source, and you can use it for any purpose, personal or commercial.
                    </p>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}